CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    menu_item_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'QUEUED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

